[project]
site_name = "Quinn's Website"
site_url = "https://quinn-dj.github.io/"
site_description = "努力成为更好的自己"
site_author = "Quinn"
docs_dir = "docs"
site_dir = "site"
use_directory_urls = true
extra_javascript = [
  "javascripts/extra.js",
  "https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js",
  "javascripts/mathjax.js",
  "https://unpkg.com/katex@0/dist/contrib/auto-render.min.js"
]
extra_css = [
  "stylesheets/extra.css",
  "stylesheets/link.css",
  "stylesheets/customize.css",
  # "https://unpkg.com/katex@0/dist/katex.min.css",
  "https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css",
]
nav = [
  { "首页" = [ { "index" = "index.md" } ] },
  { "Mathematics" = [ { "index" = "math/index.md" }, { "常微分方程" = "math/ode.md" } ] },
  { "Computing & Coding" = [ { "index" = "coding/index.md" }, { "面向对象编程" = [ { "index" = "coding/oop/index.md" }, { "C++20 介绍" = "coding/oop/chap-01.md" } ] }, { "数据结构与算法" = [ { "index" = "coding/dsa/index.md" }, { "课后作业解题报告" = "coding/dsa/report.md" } ] }, { "自己研究的小东西" = [ { "三体问题" = "coding/3body.md" }, { "Verlet 算法" = "coding/verletalgorithm.md" }, { "Cholesky 分解在不同平台上的性能异常" = "coding/cholesky_performance_anomaly.md" } ] } ] },
  { "博客" = [ { "index" = "blog/index.md" } ] },
  { "标签" = "tags.md" },
  { "友情连接" = [ { "Links" = "links/index.md" } ] },
]

[project.theme]
name = "material"
custom_dir = "docs/overrides"
language = "zh"
features = [
  "announce.dismiss",
  "navigation.tracking",
  "navigation.tabs",
  "navigation.sections",
  "navigation.top",
  "navigation.footer",
  "search.suggest",
  "search.highlight",
  "search.share",
  "navigation.expand",
  "navigation.indexes",
  "content.tabs.link",
  "content.tooltips",
  "content.code.copy",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
]

[project.theme.icon]
repo = "fontawesome/brands/github"

[[project.theme.palette]]
media = "(prefers-color-scheme)"

[project.theme.palette.toggle]
icon = "material/link"
name = "Close automatic color mode switching"

[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
primary = "indigo"
accent = "blue"

[project.theme.palette.toggle]
icon = "material/weather-sunny"
name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
primary = "black"
accent = "indigo"

[project.theme.palette.toggle]
icon = "material/weather-night"
name = "Switch to light mode"

[project.extra]
generator = true

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/quinn-dj"

[[project.extra.social]]
icon = "fontawesome/regular/envelope"
link = "mailto:<yv40403@gmail.com>"

[project.plugins.search]

[project.plugins.tags]

[project.plugins.blog]
post_date_format = "full"
draft = true
draft_if_future_date = true
post_readtime = true
post_readtime_words_per_minute = 265
post_url_format = "{date}/{slug}"
pagination_url_format = "page/{page}"
authors_file = "{blog}/.authors.yml"

[project.markdown_extensions]
abbr = {}
attr_list = {}
admonition = {}
footnotes = {}
md_in_html = {}
meta = {}
"pymdownx.caret" = {}
"pymdownx.betterem" = {}
"pymdownx.critic" = {}
"pymdownx.details" = {}
"pymdownx.inlinehilite" = {}
"pymdownx.keys" = {}
"pymdownx.mark" = {}
"pymdownx.snippets" = {}
"pymdownx.smartsymbols" = {}
"pymdownx.tilde" = {}

[project.markdown_extensions."def_list"]

[project.markdown_extensions.pymdownx.tasklist]
custom_checkbox = true

[project.markdown_extensions."pymdownx.superfences"]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format" },
]

[project.markdown_extensions.pymdownx.arithmatex]
generic = true

[project.markdown_extensions.toc]
permalink = true

[project.markdown_extensions."pymdownx.highlight"]
anchor_linenums = true
linenums = true
auto_title = true

[project.markdown_extensions."pymdownx.emoji"]
emoji_index = "material.extensions.emoji.twemoji"
emoji_generator = "material.extensions.emoji.to_svg"

[project.markdown_extensions."pymdownx.tabbed"]
alternate_style = true
